### ISSUE TITLE
Hang page (request not complete) when using ContextRunner with Vertx 3.5.0

### ISSUE THREAD

**Issue by vincentDAO** [rworsnop/vertx-beans#12]
Hi guys,

Thank you for your great job; we're using your library in our app.
Almost stuffs still work fine after we upgrade Vertx 3.5.0 except ContextRunner which worked fine with Vertx 3.4.2.

The ContextRunner will make hang page forever if browser makes bundles  of static resource requests

Here is our code:
// this code will hang the page, see attached image
`
contextRunner.executeBlocking(2,
     (Handler<AsyncResult<HttpServer>> handler) ->
                   vertx.createHttpServer()
                   .requestHandler(router::accept)
                     .listen(port, address, handler),
              1, TimeUnit.MINUTES);
`
// this code work fine
`
         vertx.createHttpServer()
            .requestHandler(router::accept)
         .listen(port, address);
      }`
![hang](https://user-images.githubusercontent.com/22828550/32584807-de1f7db8-c52c-11e7-822e-4aec8018d9c2.png)

**Comment by rworsnop** [comment]
Hi Vincent,
It would help greatly if you could provide a reproducer for this problem - preferably in a GitHub repo that I can clone.

**Comment by vincentDAO** [comment]
Ok, Let me create a simple app to reproduce the bug.

**Comment by vincentDAO** [comment]
Hi @rworsnop ,

I pushed my reproducer for this problem https://github.com/vincentDAO/vertxbeans-test-heavy
Let me know if you need my help to run it.

**Comment by slinkydeveloper** [comment]
@vincentDAO I've tested your reproducer https://github.com/vincentDAO/vertxbeans-test-heavy and this bug fix works: https://github.com/vert-x3/vertx-web/pull/739

**Comment by vincentDAO** [comment]
Thanks for your help. We will wait that fix to be merged.

**Comment by rworsnop** [comment]
Closed because it appears to be a vertx-web issue.
