### ISSUE TITLE
Support having HttpClient etc tied to event loop

### ISSUE THREAD

**Issue by rworsnop** [rworsnop/vertx-beans#2]
Things like HttpClient don't like being shared across event loops. Create a factory that ties such things to an event loop.

Some background: https://groups.google.com/forum/#!msg/vertx/JzPg259PGCw/wIWIPObRAQAJ

Perhaps this could be done with dynamic proxies.

**Comment by ieugen** [comment]
Or if it's not expensive to build, a new one using.

**Comment by rworsnop** [comment]
Add `ContextRunner.createProxy`

Then instead of this

```
@Bean
public HttpClient httpClient(Vertx vertx){
  // Oh no! We might be sharing an HttpClient across instances!
  return vertx.createHttpClient(...);
}
```

Developers would do this:

```
@Bean
public HttpClient httpClient(Vertx vertx, ContextRunner runner){
  // Inject a proxy that uses cached HttpClient if there's one on the thread,
  // otherwise use the Supplier to create one (and put it on the thread).
  return runner.createProxy(()->vertx.createHttpClient(...));
}
```

**Comment by ieugen** [comment]
Nice. Thanks. Should this be applied to RedisClients also?

**Comment by rworsnop** [comment]
That seems a safe assumption. I'm going to take another look at this, though. The background link I posted refers to sharing requests across contexts, not just a client. However, where I work I think we've seen problems with sharing clients but not requests.

**Comment by rworsnop** [comment]
Duh.... I just remembered that Spring has already solved this problem with custom scopes. I have updated the README.
