### ISSUE TITLE
Missing properties for VertxOptions

### ISSUE THREAD

**Issue by phsmip** [rworsnop/vertx-beans#9]
Hi Sir,

The following properties are not taken into account when initializing VertxOptions bean:
`vertx.cluster.public.host`
`vertx.cluster.public.port`

These properties are useful when you are running Vertx in a container environment.
Could you please add the following lines into VetxBeansBase class:
`setParameter(env.getProperty("vertx.cluster.public.host", String.class), options::setClusterPublicHost);`
`setParameter(env.getProperty("vertx.cluster.public.port", Integer.class), options::setClusterPublicPort);`

Thank you.

Regards

Suray Ph.

**Comment by rworsnop** [comment]
Please submit a pull request.
